Remove all instances of floating promises in processor
kitspace/kitspace-v2 pull request #516
Opened 2022-11-29 13:07 UTC by kasbah

Seems like the style I adopted of just "floating" all the `job.updateProgress` makes things less predictable without much gain.

2022-11-30 04:31 UTC, AbdulrhmnGhanem approved these changes

2022-11-30 04:44 UTC, AbdulrhmnGhanem requested changes
It no longer falls back to the repo description if there is no summary: this is why e2e is failing

https://cloud.cypress.io/projects/d8hk55/runs/1a2ede29-4de4-457e-9bf0-5c7042de2826/test-results/41be2e63-d76f-40a9-877b-b43bc9db0ab2

2022-11-30 11:12 UTC, kasbah commented
So it's unrelated to this code right? The Github API is failing us? Probably related to #480 then.

2022-12-01 19:32 UTC, AbdulrhmnGhanem approved these changes

2022-12-01 19:32 UTC, merged